<?php

/**
 * BaseTestArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * 
 * @method string      getTitle() Returns the current record's "title" value
 * @method TestArticle setTitle() Sets the current record's "title" value
 * 
 * @package    ##PROJECT_NAME##
 * @subpackage model
 * @author     ##AUTHOR_NAME##
 * @version    SVN: $Id: BaseTestArticle.class.php 29482 2010-05-16 17:11:45Z bicou $
 */
abstract class BaseTestArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('test_article');
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $gearmanable0 = new Doctrine_Template_Gearmanable(array(
             'events' => 
             array(
              0 => 'insert',
              1 => 'update',
              2 => 'delete',
             ),
             ));
        $this->actAs($gearmanable0);
    }
}